# 1. Standard Port for this microservice
server.port=8081

# 2. Match the name of the .yml file you created on GitHub
spring.application.name=video-service

# 3. Connection to the Config Server (Port 8888)
# This replaces the need for any other settings here (like DB credentials)
spring.config.import=optional:configserver:http://localhost:8888

# 4. (Optional) Force the app to join Eureka immediately
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/